#cloud-config
users:
  - default
  - name: yc-user
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDM0bfBUxQJK9GgVjnH+at1zmq+RFp3QTwCS8tyH6x+U78ZLmpiFWZqG8BuTpyKE8Hk5vZjExKfuSjo+HWk/8kvhp4JBLbIqIAZSkt9nk3kUKWHwfMPCyDAYBTfX768kamGaRlftKYrrQLxVw10qOnYW0Bdpu759Z+30yOZjpsgKIEiMXkwVjeLZi8QewqY9AufoCx0OMCwc9slwsZAPgGg9Vhm4IQczYEw8uU5v61JShMrBZx4QMYtqWon4v9qfF0vm54uXXwWbhrcjuSqyXZF+/O+gMp8nGuzCxkU+VkB4XRhZusXrKm7peW9xR6YTgjP10+YJPArJPW7r2CO4Irfe0FjkhHq9ZipzJOBLydqagis7oWzVm5DsW9VbGIAdTWywoEQg7IHokNIH1hTsUDXcmWyEuSBYFs/ua+24fW9tfwClmByAhQnx/DGijtlKWngb6Wv5hkt5drJAEkO4+8ey78X3orS39O9dIbc/bAXWjPPhOXvLGMQcahF2MR6xgc= appuser

runcmd:
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list

  - sudo apt install -y apt-transport-https ca-certificates
  - sudo apt -y update
  - sudo apt install -y git ruby-full ruby-bundler build-essential mongodb-org

  - sudo systemctl start mongod
  - sudo systemctl enable mongod

  - cd /root
  - git clone -b monolith https://github.com/express42/reddit.git
  - cd reddit
  - bundle install
  - puma -d
